apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: jx-basic-auth
  name: jx-tenant-service
spec:
  rules:
  - host: jx-tenant-service-jx-staging.{{ .Values.expose.config.domain }}
    http:
      paths:
      - backend:
          serviceName: jx-jx-tenant-serice
          servicePort: 80
  tls:
  - hosts:
    - jx-tenant-service-jx-staging.{{ .Values.expose.config.domain }}
    secretName: tls-jenkins-x-live-p
