PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: jenkins-x.live
    exposer: Ingress
    http: "false"
    tlsacme: "true"
jenkins:
  Servers:
    Global: {}
prow: {}

jx-tenant-service:
  replicaCount: 1
  parentDomain: jxaas.io
  parentProject: cb-aps-poc
  parentDNSZone: jxaas-io-parent
  dbPassword: vault:tekton-weasel/staging/jx-tenant-service-db:password
  sa: vault:tekton-weasel/staging/jx-tenant-service-sa:json
  dbInstance: jenkins-x-infra:europe-west1:staging-jx-tenant-db=tcp:5432
  service:
    serviceAnnotations:
      fabric8.io/expose: "false"
      fabric8.io/exposeUrl: https://jx-tenant-service-jx-staging.jenkins-x.live
